# Generated by Django 3.0.2 on 2020-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20200123_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='ddd', unique=True),
            preserve_default=False,
        ),
    ]
