# Generated by Django 3.0.2 on 2020-01-24 16:16

from django.db import migrations
from django.utils.text import slugify

cities = ('Nantes', 'Rennes', 'Paris', 'Lille', 'Caen', 'Coudray')


def load_cities(apps, schema_editor):
    City = apps.get_model('venues', 'City')

    for city in cities:
        City.objects.update_or_create(
            slug=slugify(city),
            defaults={
                'name': city,
                'active': True
            })


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_city_slug'),
    ]

    operations = [
        migrations.RunPython(load_cities),
    ]
