# Generated by Django 3.0.2 on 2020-02-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_cities_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
